# Generated by Django 5.1.3 on 2025-01-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizclass',
            name='account_mail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
