# Generated by Django 5.1.3 on 2025-01-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_quiz_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answers',
            field=models.JSONField(default=dict),
        ),
    ]
