# Generated by Django 5.1.3 on 2025-01-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_quiz_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizclass',
            name='account_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
