# Generated by Django 5.1.3 on 2025-01-15 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_quizclass_account_mail'),
        ('dashboard', '0006_alter_quizclass_account_mail'),
    ]

    operations = [
    ]
